name: Deploy GitHub Pages from Tarefa_4/public

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/upload-artifact@v4

      - name: Check if index.html exists
        run: |
          if [ ! -f ./Tarefa_4/public/index.html ]; then
            echo "Erro: Tarefa_4/public/index.html não encontrado."
            exit 1
          fi

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact from Tarefa_4/public
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./Tarefa_4/public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
